# vim: ft=dockerfile

FROM golang:1.12-stretch

ARG PROTOC_VERSION=3.9.0
ARG PROTOC_FILE=protoc-${PROTOC_VERSION}-linux-x86_64.zip
ARG GOGO_VERSION=1.2.1

RUN go get github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
RUN GO111MODULE=on go get github.com/gogo/protobuf/protoc-gen-gofast@v${GOGO_VERSION}

RUN apt-get update -qq && apt-get install unzip -y
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_FILE} && \
  echo "15e395b648a1a6dda8fd66868824a396e9d3e89bc2c8648e3b9ab9801bea5d55 ${PROTOC_FILE}" | sha256sum -c - && \
  unzip ${PROTOC_FILE} -d /usr
