// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// MempoolTransaction is an object representing the database table.
type MempoolTransaction struct {
	Rowid int    `boil:"rowid" json:"rowid" toml:"rowid" yaml:"rowid"`
	Raw   []byte `boil:"raw" json:"raw" toml:"raw" yaml:"raw"`

	R *mempoolTransactionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L mempoolTransactionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MempoolTransactionColumns = struct {
	Rowid string
	Raw   string
}{
	Rowid: "rowid",
	Raw:   "raw",
}

// Generated where

var MempoolTransactionWhere = struct {
	Rowid whereHelperint
	Raw   whereHelper__byte
}{
	Rowid: whereHelperint{field: `rowid`},
	Raw:   whereHelper__byte{field: `raw`},
}

// MempoolTransactionRels is where relationship names are stored.
var MempoolTransactionRels = struct {
}{}

// mempoolTransactionR is where relationships are stored.
type mempoolTransactionR struct {
}

// NewStruct creates a new relationship struct
func (*mempoolTransactionR) NewStruct() *mempoolTransactionR {
	return &mempoolTransactionR{}
}

// mempoolTransactionL is where Load methods for each relationship are stored.
type mempoolTransactionL struct{}

var (
	mempoolTransactionColumns               = []string{"rowid", "raw"}
	mempoolTransactionColumnsWithoutDefault = []string{"raw"}
	mempoolTransactionColumnsWithDefault    = []string{"rowid"}
	mempoolTransactionPrimaryKeyColumns     = []string{"rowid"}
)

type (
	// MempoolTransactionSlice is an alias for a slice of pointers to MempoolTransaction.
	// This should generally be used opposed to []MempoolTransaction.
	MempoolTransactionSlice []*MempoolTransaction
	// MempoolTransactionHook is the signature for custom MempoolTransaction hook methods
	MempoolTransactionHook func(context.Context, boil.ContextExecutor, *MempoolTransaction) error

	mempoolTransactionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	mempoolTransactionType                 = reflect.TypeOf(&MempoolTransaction{})
	mempoolTransactionMapping              = queries.MakeStructMapping(mempoolTransactionType)
	mempoolTransactionPrimaryKeyMapping, _ = queries.BindMapping(mempoolTransactionType, mempoolTransactionMapping, mempoolTransactionPrimaryKeyColumns)
	mempoolTransactionInsertCacheMut       sync.RWMutex
	mempoolTransactionInsertCache          = make(map[string]insertCache)
	mempoolTransactionUpdateCacheMut       sync.RWMutex
	mempoolTransactionUpdateCache          = make(map[string]updateCache)
	mempoolTransactionUpsertCacheMut       sync.RWMutex
	mempoolTransactionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var mempoolTransactionBeforeInsertHooks []MempoolTransactionHook
var mempoolTransactionBeforeUpdateHooks []MempoolTransactionHook
var mempoolTransactionBeforeDeleteHooks []MempoolTransactionHook
var mempoolTransactionBeforeUpsertHooks []MempoolTransactionHook

var mempoolTransactionAfterInsertHooks []MempoolTransactionHook
var mempoolTransactionAfterSelectHooks []MempoolTransactionHook
var mempoolTransactionAfterUpdateHooks []MempoolTransactionHook
var mempoolTransactionAfterDeleteHooks []MempoolTransactionHook
var mempoolTransactionAfterUpsertHooks []MempoolTransactionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MempoolTransaction) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MempoolTransaction) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MempoolTransaction) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MempoolTransaction) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MempoolTransaction) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MempoolTransaction) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MempoolTransaction) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MempoolTransaction) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MempoolTransaction) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range mempoolTransactionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMempoolTransactionHook registers your hook function for all future operations.
func AddMempoolTransactionHook(hookPoint boil.HookPoint, mempoolTransactionHook MempoolTransactionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		mempoolTransactionBeforeInsertHooks = append(mempoolTransactionBeforeInsertHooks, mempoolTransactionHook)
	case boil.BeforeUpdateHook:
		mempoolTransactionBeforeUpdateHooks = append(mempoolTransactionBeforeUpdateHooks, mempoolTransactionHook)
	case boil.BeforeDeleteHook:
		mempoolTransactionBeforeDeleteHooks = append(mempoolTransactionBeforeDeleteHooks, mempoolTransactionHook)
	case boil.BeforeUpsertHook:
		mempoolTransactionBeforeUpsertHooks = append(mempoolTransactionBeforeUpsertHooks, mempoolTransactionHook)
	case boil.AfterInsertHook:
		mempoolTransactionAfterInsertHooks = append(mempoolTransactionAfterInsertHooks, mempoolTransactionHook)
	case boil.AfterSelectHook:
		mempoolTransactionAfterSelectHooks = append(mempoolTransactionAfterSelectHooks, mempoolTransactionHook)
	case boil.AfterUpdateHook:
		mempoolTransactionAfterUpdateHooks = append(mempoolTransactionAfterUpdateHooks, mempoolTransactionHook)
	case boil.AfterDeleteHook:
		mempoolTransactionAfterDeleteHooks = append(mempoolTransactionAfterDeleteHooks, mempoolTransactionHook)
	case boil.AfterUpsertHook:
		mempoolTransactionAfterUpsertHooks = append(mempoolTransactionAfterUpsertHooks, mempoolTransactionHook)
	}
}

// One returns a single mempoolTransaction record from the query.
func (q mempoolTransactionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MempoolTransaction, error) {
	o := &MempoolTransaction{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for mempool_transaction")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MempoolTransaction records from the query.
func (q mempoolTransactionQuery) All(ctx context.Context, exec boil.ContextExecutor) (MempoolTransactionSlice, error) {
	var o []*MempoolTransaction

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MempoolTransaction slice")
	}

	if len(mempoolTransactionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MempoolTransaction records in the query.
func (q mempoolTransactionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count mempool_transaction rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q mempoolTransactionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if mempool_transaction exists")
	}

	return count > 0, nil
}

// MempoolTransactions retrieves all the records using an executor.
func MempoolTransactions(mods ...qm.QueryMod) mempoolTransactionQuery {
	mods = append(mods, qm.From("\"mempool_transaction\""))
	return mempoolTransactionQuery{NewQuery(mods...)}
}

// FindMempoolTransaction retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMempoolTransaction(ctx context.Context, exec boil.ContextExecutor, rowid int, selectCols ...string) (*MempoolTransaction, error) {
	mempoolTransactionObj := &MempoolTransaction{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"mempool_transaction\" where \"rowid\"=$1", sel,
	)

	q := queries.Raw(query, rowid)

	err := q.Bind(ctx, exec, mempoolTransactionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from mempool_transaction")
	}

	return mempoolTransactionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MempoolTransaction) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no mempool_transaction provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mempoolTransactionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	mempoolTransactionInsertCacheMut.RLock()
	cache, cached := mempoolTransactionInsertCache[key]
	mempoolTransactionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			mempoolTransactionColumns,
			mempoolTransactionColumnsWithDefault,
			mempoolTransactionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(mempoolTransactionType, mempoolTransactionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(mempoolTransactionType, mempoolTransactionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"mempool_transaction\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"mempool_transaction\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into mempool_transaction")
	}

	if !cached {
		mempoolTransactionInsertCacheMut.Lock()
		mempoolTransactionInsertCache[key] = cache
		mempoolTransactionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MempoolTransaction.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MempoolTransaction) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	mempoolTransactionUpdateCacheMut.RLock()
	cache, cached := mempoolTransactionUpdateCache[key]
	mempoolTransactionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			mempoolTransactionColumns,
			mempoolTransactionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update mempool_transaction, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"mempool_transaction\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, mempoolTransactionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(mempoolTransactionType, mempoolTransactionMapping, append(wl, mempoolTransactionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update mempool_transaction row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for mempool_transaction")
	}

	if !cached {
		mempoolTransactionUpdateCacheMut.Lock()
		mempoolTransactionUpdateCache[key] = cache
		mempoolTransactionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q mempoolTransactionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for mempool_transaction")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for mempool_transaction")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MempoolTransactionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mempoolTransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"mempool_transaction\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, mempoolTransactionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in mempoolTransaction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all mempoolTransaction")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MempoolTransaction) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no mempool_transaction provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(mempoolTransactionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	mempoolTransactionUpsertCacheMut.RLock()
	cache, cached := mempoolTransactionUpsertCache[key]
	mempoolTransactionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			mempoolTransactionColumns,
			mempoolTransactionColumnsWithDefault,
			mempoolTransactionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			mempoolTransactionColumns,
			mempoolTransactionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert mempool_transaction, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(mempoolTransactionPrimaryKeyColumns))
			copy(conflict, mempoolTransactionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"mempool_transaction\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(mempoolTransactionType, mempoolTransactionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(mempoolTransactionType, mempoolTransactionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert mempool_transaction")
	}

	if !cached {
		mempoolTransactionUpsertCacheMut.Lock()
		mempoolTransactionUpsertCache[key] = cache
		mempoolTransactionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MempoolTransaction record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MempoolTransaction) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MempoolTransaction provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), mempoolTransactionPrimaryKeyMapping)
	sql := "DELETE FROM \"mempool_transaction\" WHERE \"rowid\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from mempool_transaction")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for mempool_transaction")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q mempoolTransactionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no mempoolTransactionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from mempool_transaction")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for mempool_transaction")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MempoolTransactionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MempoolTransaction slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(mempoolTransactionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mempoolTransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"mempool_transaction\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, mempoolTransactionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from mempoolTransaction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for mempool_transaction")
	}

	if len(mempoolTransactionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MempoolTransaction) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMempoolTransaction(ctx, exec, o.Rowid)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MempoolTransactionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MempoolTransactionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), mempoolTransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"mempool_transaction\".* FROM \"mempool_transaction\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, mempoolTransactionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MempoolTransactionSlice")
	}

	*o = slice

	return nil
}

// MempoolTransactionExists checks if the MempoolTransaction row exists.
func MempoolTransactionExists(ctx context.Context, exec boil.ContextExecutor, rowid int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"mempool_transaction\" where \"rowid\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, rowid)
	}

	row := exec.QueryRowContext(ctx, sql, rowid)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if mempool_transaction exists")
	}

	return exists, nil
}
