// Code generated by "stringer -type=ObjectStatus"; DO NOT EDIT.

package catalog

import "strconv"

const _ObjectStatus_name = "StatusUnknownStatusOKStatusNotFoundStatusInternalErrorStatusUpstreamUnreachableStatusUpstreamError"

var _ObjectStatus_index = [...]uint8{0, 13, 21, 35, 54, 79, 98}

func (i ObjectStatus) String() string {
	if i < 0 || i >= ObjectStatus(len(_ObjectStatus_index)-1) {
		return "ObjectStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectStatus_name[_ObjectStatus_index[i]:_ObjectStatus_index[i+1]]
}
