// Code generated by "stringer -type=ObjectStatus"; DO NOT EDIT.

package catalog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusOK-1]
	_ = x[StatusNotFound-2]
	_ = x[StatusNotModified-3]
	_ = x[StatusInternalError-4]
	_ = x[StatusUpstreamUnreachable-5]
	_ = x[StatusUpstreamError-6]
}

const _ObjectStatus_name = "StatusUnknownStatusOKStatusNotFoundStatusNotModifiedStatusInternalErrorStatusUpstreamUnreachableStatusUpstreamError"

var _ObjectStatus_index = [...]uint8{0, 13, 21, 35, 52, 71, 96, 115}

func (i ObjectStatus) String() string {
	if i < 0 || i >= ObjectStatus(len(_ObjectStatus_index)-1) {
		return "ObjectStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectStatus_name[_ObjectStatus_index[i]:_ObjectStatus_index[i+1]]
}
