package kv

import (
	"testing"

	"github.com/pkg/errors"
	"github.com/stretchr/testify/assert"
)

func basicTest(t *testing.T, c *Client) {
	_, err := c.CASUint64("notexist", []byte{}, 1, 2)
	assert.Equal(t, err, ErrUnsetValue)

	_, _, err = c.GetUint64("uint")
	assert.Equal(t, err, ErrUnsetValue)

	nonce, err := c.SetUint64("uint", 1)
	assert.Nil(t, err)
	uintOut, _, err := c.GetUint64("uint")
	assert.Nil(t, err)
	assert.Equal(t, uint64(1), uintOut)
	_, err = c.CASUint64("uint", nonce, 0, 2)
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASUint64("uint", []byte{1, 2, 3, 4}, 1, 2)
	assert.Equal(t, err, ErrNotEqual)
	newnonce, err := c.CASUint64("uint", nonce, 1, 2)
	assert.Nil(t, err)
	assert.NotEqual(t, newnonce, nonce)
	uintOut, _, err = c.GetUint64("uint")
	assert.Nil(t, err)
	assert.Equal(t, uint64(2), uintOut)

	_, _, err = c.GetInt64("int")
	assert.Equal(t, err, ErrUnsetValue)
	nonce, err = c.SetInt64("int", -1)
	assert.Nil(t, err)
	intOut, _, err := c.GetInt64("int")
	assert.Nil(t, err)
	assert.Equal(t, int64(-1), intOut)
	_, err = c.CreateInt64("int", 0)
	assert.Equal(t, errors.Cause(err), ErrAlreadySet)
	_, err = c.CreateInt64("int2", 0)
	assert.Nil(t, err)
	_, err = c.CASInt64("int", nonce, 0, -2)
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASInt64("int", []byte{1, 2, 3, 4}, -1, -2)
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASInt64("int", nonce, -1, -2)
	assert.Nil(t, err)
	intOut, _, err = c.GetInt64("int")
	assert.Nil(t, err)
	assert.Equal(t, int64(-2), intOut)

	_, _, err = c.GetFloat64("float")
	assert.Equal(t, err, ErrUnsetValue)
	nonce, err = c.SetFloat64("float", -1.2)
	assert.Nil(t, err)
	floatOut, _, err := c.GetFloat64("float")
	assert.Nil(t, err)
	assert.Equal(t, float64(-1.2), floatOut)
	_, err = c.CreateFloat64("float", 0)
	assert.Equal(t, errors.Cause(err), ErrAlreadySet)
	_, err = c.CreateFloat64("float2", 0)
	assert.Nil(t, err)
	_, err = c.CASFloat64("float", nonce, -1.1, -2.4)
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASFloat64("float", []byte{1, 2, 3, 4}, -1.2, -2.4)
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASFloat64("float", nonce, -1.2, -2.4)
	assert.Nil(t, err)
	floatOut, _, err = c.GetFloat64("float")
	assert.Nil(t, err)
	assert.Equal(t, float64(-2.4), floatOut)

	_, _, err = c.GetString("str")
	assert.Equal(t, err, ErrUnsetValue)
	nonce, err = c.SetString("str", "hello")
	assert.Nil(t, err)
	strOut, _, err := c.GetString("str")
	assert.Nil(t, err)
	assert.Equal(t, "hello", strOut)
	_, err = c.CreateString("str", "asdf")
	assert.Equal(t, errors.Cause(err), ErrAlreadySet)
	_, err = c.CreateString("str2", "asdf")
	assert.Nil(t, err)
	_, err = c.CASString("str", nonce, "nope", "world")
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASString("str", []byte{1, 2, 3, 4}, "hello", "world")
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASString("str", nonce, "hello", "world")
	assert.Nil(t, err)
	strOut, _, err = c.GetString("str")
	assert.Nil(t, err)
	assert.Equal(t, "world", strOut)

	_, _, err = c.GetBytes("bytes")
	assert.Equal(t, err, ErrUnsetValue)
	nonce, err = c.SetBytes("bytes", []byte{0, 1, 0, 1})
	assert.Nil(t, err)
	_, err = c.CreateBytes("bytes", []byte{0, 1, 1, 1})
	assert.Equal(t, errors.Cause(err), ErrAlreadySet)
	_, err = c.CreateBytes("bytes2", []byte{0, 1, 1, 1})
	assert.Nil(t, err)
	_, err = c.CASBytes("bytes", nonce, []byte{1, 0, 1, 0}, []byte{1, 0, 1, 0})
	assert.Equal(t, err, ErrNotEqual)
	_, err = c.CASBytes("bytes", nonce, []byte{0, 1, 0, 1}, []byte{1, 0, 1, 0})
	assert.Nil(t, err)
}
