// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Bundle       string
	Cache        string
	Escrow       string
	EscrowCaches string
}{
	Bundle:       "bundle",
	Cache:        "cache",
	Escrow:       "escrow",
	EscrowCaches: "escrow_caches",
}
